#!/bin/bash

BUCKET="pic-r2"
ACCOUNT_ID="ed3e4f0448b71302675f2b436e5e8dd3"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║              删除 R2 存储桶: $BUCKET                         ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "存储桶信息:"
wrangler r2 bucket info $BUCKET
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  警告: 此存储桶包含 949 个对象 (3.36 GB)"
echo ""
echo "由于对象数量较多，建议通过 Cloudflare Dashboard 删除："
echo ""
echo "🔗 https://dash.cloudflare.com/$ACCOUNT_ID/r2/buckets/$BUCKET"
echo ""
echo "Dashboard 提供批量删除功能，速度更快。"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
