import { ProcessorBindings, AI_MODELS } from '@lens/shared';

/**
 * LENS FINANCIAL GUARDIAN (The Oracle)
 * An industrial-grade GraphQL client designed for Cloudflare Edge.
 * Featuring: Zero-trust error handling, exponential backoff, and financial isolation.
 */

const GRAPHQL_ENDPOINT = 'https://api.cloudflare.com/client/v4/graphql';

interface BillingSummary {
  evolutionCost: number;
  totalTokens: number;
}

interface GraphQLResponse {
  data?: {
    viewer: {
      accounts: Array<{
        aiGatewayRequestsAdaptiveGroups: Array<{
          sum: {
            cost: number;
            uncachedTokensIn: number;
            uncachedTokensOut: number;
          };
          dimensions: {
            model: string;
          };
        }>;
      }>;
    };
  };
  errors?: Array<{ message: string }>;
}

/**
 * Robust fetch wrapper with exponential backoff for critical financial calls.
 */
async function robustFetch(url: string, options: RequestInit, retries = 3): Promise<Response> {
  for (let i = 0; i < retries; i++) {
    try {
      const response = await fetch(url, options);
      if (response.ok) return response;
      if (response.status === 401 || response.status === 403) return response; // Immediate fail on auth
    } catch (e) {
      if (i === retries - 1) throw e;
    }
    await new Promise((r) => setTimeout(r, Math.pow(2, i) * 1000));
  }
  throw new Error('All retry attempts exhausted');
}

/**
 * Fetches the USD cost specifically generated by the flagship model.
 * Implements "Pulse Check" logic to ensure environment sanity.
 */
export async function getSystemUsageSummary(env: ProcessorBindings): Promise<BillingSummary> {
  // Env Sanity Check
  if (!env.CLOUDFLARE_API_TOKEN || env.CLOUDFLARE_API_TOKEN.length < 10) {
    console.error('🚫 CRITICAL: Invalid CLOUDFLARE_API_TOKEN detected.');
    return { evolutionCost: 0, totalTokens: 0 };
  }

  const today = new Date().toISOString().split('T')[0] + 'T00:00:00Z';
  const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0] + 'T00:00:00Z';

  const query = `
    query GetAIGatewayUsage($accountTag: String!, $gateway: String!, $start: String!, $end: String!) {
      viewer {
        accounts(filter: { accountTag: $accountTag }) {
          aiGatewayRequestsAdaptiveGroups(
            limit: 100,
            filter: { gateway: $gateway, datetimeHour_geq: $start, datetimeHour_lt: $end }
          ) {
            sum { cost uncachedTokensIn uncachedTokensOut }
            dimensions { model }
          }
        }
      }
    }
  `;

  try {
    const response = await robustFetch(GRAPHQL_ENDPOINT, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${env.CLOUDFLARE_API_TOKEN}`,
      },
      body: JSON.stringify({
        query,
        variables: {
          accountTag: env.CLOUDFLARE_ACCOUNT_ID,
          gateway: 'lens-gateway',
          start: today,
          end: tomorrow,
        },
      }),
    });

    if (!response.ok) {
      console.warn(`⚠️ Financial audit API returned ${response.status}. Budgeting 0 for safety.`);
      return { evolutionCost: 0, totalTokens: 0 };
    }

    const result = (await response.json()) as GraphQLResponse;
    if (result.errors) {
      console.error('❌ GraphQL Logic Errors:', result.errors.map((e) => e.message).join(', '));
      return { evolutionCost: 0, totalTokens: 0 };
    }

    const groups = result.data?.viewer?.accounts?.[0]?.aiGatewayRequestsAdaptiveGroups || [];

    return groups.reduce(
      (acc: BillingSummary, group) => {
        if (group.dimensions.model === AI_MODELS.TEXT) {
          acc.evolutionCost += group.sum.cost || 0;
          acc.totalTokens += (group.sum.uncachedTokensIn || 0) + (group.sum.uncachedTokensOut || 0);
        }
        return acc;
      },
      { evolutionCost: 0, totalTokens: 0 },
    );
  } catch (error) {
    console.error('💥 Critical Audit Crash:', error);
    return { evolutionCost: 0, totalTokens: 0 };
  }
}

/**
 * Calculates evolution capacity with a built-in safety margin (5%).
 */
export async function calculateEvolutionCapacity(env: ProcessorBindings, dailyLimit: number): Promise<number> {
  const summary = await getSystemUsageSummary(env);
  const remainingUSD = dailyLimit - summary.evolutionCost;

  // High-precision estimation with safety buffer
  const estimatedCostPerImage = 0.001;

  if (remainingUSD <= 0) return 0;
  return Math.floor((remainingUSD * 0.95) / estimatedCostPerImage);
}
